# Generated by Django 5.2.9 on 2025-12-04 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Tipo de dato del atributo (Ej: Texto, Número, Fecha)', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo del atributo (Ej: Color, Peso, Ubicación)', max_length=255)),
            ],
            options={
                'verbose_name': 'Atributo Maestro',
                'verbose_name_plural': 'Atributos Maestros',
                'db_table': 'attribute',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
                'db_table': 'catalog',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.IntegerField(blank=True, null=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.catalog')),
            ],
            options={
                'verbose_name': 'Catálogo-Ítem',
                'verbose_name_plural': 'Catálogo-Ítems',
                'db_table': 'catalog_item',
            },
        ),
        migrations.CreateModel(
            name='InventoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='client_app.attribute')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.inventory')),
            ],
            options={
                'verbose_name': 'Inventario-Atributo',
                'verbose_name_plural': 'Inventario-Atributos',
                'db_table': 'inventory_attribute',
                'unique_together': {('inventory', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='attributes',
            field=models.ManyToManyField(related_name='inventories_associated', through='client_app.InventoryAttribute', to='client_app.attribute'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('catalogs', models.ManyToManyField(related_name='cataloged_items', through='client_app.CatalogItem', to='client_app.catalog')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='client_app.inventory')),
            ],
            options={
                'verbose_name': 'Ítem',
                'verbose_name_plural': 'Ítems',
                'db_table': 'item',
            },
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.item'),
        ),
        migrations.CreateModel(
            name='ItemAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='client_app.attribute')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.item')),
            ],
            options={
                'verbose_name': 'Valor de Atributo de Ítem',
                'verbose_name_plural': 'Valores de Atributo de Ítems',
                'db_table': 'item_attribute_value',
                'unique_together': {('item', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='attributes',
            field=models.ManyToManyField(related_name='items_with_value', through='client_app.ItemAttributeValue', to='client_app.attribute'),
        ),
    ]
