# Generated by Django 5.2.9 on 2025-12-04 20:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Privilegio',
                'verbose_name_plural': 'Privilegios',
                'db_table': 'privilege',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('state', models.BooleanField(default=True)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('tenant_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'verbose_name': 'Usuario Interno',
                'verbose_name_plural': 'Usuarios Internos',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='PrivilegeRole',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.privilege')),
            ],
            options={
                'verbose_name': 'Privilegio-Rol',
                'verbose_name_plural': 'Privilegios-Roles',
                'db_table': 'privilege_role',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('privileges', models.ManyToManyField(related_name='roles_with_privilege', through='client_app.PrivilegeRole', to='client_app.privilege')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
            },
        ),
        migrations.AddField(
            model_name='privilegerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.role'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.user')),
            ],
            options={
                'verbose_name': 'Usuario-Rol',
                'verbose_name_plural': 'Usuarios-Roles',
                'db_table': 'user_role',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users_with_role', through='client_app.UserRole', to='client_app.role'),
        ),
    ]
